quarkus:
  application:
    name: tinder-ai-backend
  
  http:
    cors:
      ~: true
      origins: "*"

  langchain4j:
    openai:
      api-key: ${QUARKUS_AI_OPEN_AI_API_KEY}


  # Mongo DB
  mongodb:
    devservices:
      port: 63556
    database: tinder-ai
